name: flutter_currency
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  json_serializable: 6.2.0
  json_annotation: 4.5.0
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true
